In [1]:
from __future__ import print_function

from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

/root/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [2]:
import tensorflow as tf
import numpy as np

In [3]:
dir(mnist.train)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_epochs_completed',
 '_images',
 '_index_in_epoch',
 '_labels',
 '_num_examples',
 'epochs_completed',
 'images',
 'labels',
 'next_batch',
 'num_examples']

In [4]:
mnist.train.num_examples

55000

In [5]:
train_batch,label_batch =mnist.train.next_batch(100)

In [6]:
train_batch.shape

(100, 784)

In [7]:
label_batch.shape

(100, 10)

In [8]:
np.shape(mnist.train.images)

(55000, 784)

In [9]:
np.shape(mnist.train.labels)

(55000, 10)

In [10]:
def print_ds(sess,ds,head=None):
    count = 0
    print(type(ds))
    #if isinstance(ds,tf.data.Dataset) or isinstance(ds,tf.contrib.learn.datasets.mnist.DataSet):
    init = tf.global_variables_initializer()
    sess.run(init)
    iter = ds.make_one_shot_iterator()
    make_one_shot_iterator
    while True:
    
        try:
            print(sess.run(iter.get_next()))
            count = count +1
            if head!=None:
                if count==head:
                    # 如果指定了只打印topk个
                    break
            # 如果未指定head，则打印所有
        except Exception as e:
            break
            pass
    print("the count%d"%count)

In [11]:
sess = tf.Session()

In [12]:
# 总共有10个类别
n_class=10
w = tf.Variable(tf.truncated_normal(shape=[784,n_class],dtype=tf.float32,mean=0,stddev=1))


In [13]:
def test_soft_max():
    with tf.variable_scope("test",reuse=tf.AUTO_REUSE):
        t = tf.get_variable(name='t',shape=[3,3],initializer=tf.random_normal_initializer(mean=0,stddev=1,dtype=tf.float32))
        # 使用soft
        soft_t = tf.nn.softmax(logits=t,name='pros')
        init = tf.global_variables_initializer()
        sess.run(init)
        result = sess.run(soft_t)
        print("result:",result)
        # 求和，
        sum_result= tf.reduce_sum(result,axis=1)
        
        print("sum:",sess.run(sum_result))
        
test_soft_max()
    
    

result: [[0.28469744 0.05337682 0.6619258 ]
 [0.22725219 0.57093334 0.20181449]
 [0.36078554 0.58519757 0.05401689]]
sum: [1. 1. 1.]


In [14]:
n_class=10
w = tf.get_variable(shape=[784,n_class],name='w',initializer=tf.contrib.layers.xavier_initializer())
b = tf.Variable(tf.zeros(shape=[n_class]))
# 定义placeholder用于获取输入,第一个参数为接收的batch_size
x = tf.placeholder(shape=[None,784],dtype=tf.float32)
y_true = tf.placeholder(shape=[None,10],dtype=tf.float32)
# 获取每一个的y_pred  tf.nn.softmax,因为使用with_logits,不需要自行归一化
y_pred = tf.matmul(x,w)+b
loss_multi = tf.nn.softmax_cross_entropy_with_logits_v2(logits=y_pred,labels=y_true)


In [15]:



# 定义损失函数,使用交叉熵损失
# 一个batch中的损失

loss = tf.reduce_mean(loss_multi)

In [16]:
# 定义优化方法
opt = tf.train.GradientDescentOptimizer(name="train_1",learning_rate=0.01)
train_op = opt.minimize(loss)

In [17]:
init = tf.global_variables_initializer()
sess.run(init)
show_progress = 200
batch_size=400
epoch = 10000
train_datas = mnist.train
for i in range(epoch):
    train_batch,label_batch = train_datas.next_batch(batch_size=batch_size)
    #print(type(train_batch))
    #进行训练，并且获取相关的损失
    _,loss_result = sess.run([train_op,loss],feed_dict={x:train_batch,y_true:label_batch})
    if i%show_progress==0:
        #print("len(loss):",len(loss_result))
        print("loss:",loss_result)
        

loss: 2.3771138
loss: 1.2307539
loss: 0.9240787
loss: 0.75752634
loss: 0.6611726
loss: 0.65738463
loss: 0.58318883
loss: 0.56369513
loss: 0.5518216
loss: 0.5417503
loss: 0.48612326
loss: 0.49815026
loss: 0.4814637
loss: 0.4252578
loss: 0.46111825
loss: 0.4700828
loss: 0.4677924
loss: 0.44984964
loss: 0.41083214
loss: 0.41195238
loss: 0.43869385
loss: 0.4111731
loss: 0.4174053
loss: 0.37041128
loss: 0.4926011
loss: 0.33824566
loss: 0.3478462
loss: 0.32194147
loss: 0.3684188
loss: 0.30450782
loss: 0.38360527
loss: 0.36700165
loss: 0.45263138
loss: 0.39067432
loss: 0.44632122
loss: 0.36268955
loss: 0.35953736
loss: 0.42020386
loss: 0.3921723
loss: 0.33729523
loss: 0.3331939
loss: 0.3385606
loss: 0.34707195
loss: 0.31109297
loss: 0.38045272
loss: 0.33754548
loss: 0.45249993
loss: 0.36806288
loss: 0.4074459
loss: 0.3528238


In [18]:
# 计算相关的精确率
y_test_pred = sess.run(y_pred,feed_dict={x:mnist.test.images})
# 判断类别是否相等
y_is_equal = tf.equal(tf.arg_max(y_test_pred,dimension=1),tf.arg_max(mnist.test.labels,dimension=1))
# 计算精确率
accu = tf.reduce_mean(tf.cast(y_is_equal,tf.float32))

Instructions for updating:
Use `argmax` instead


In [19]:
sess.run(accu)

0.9108

In [20]:
label_batch[0]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [21]:
# 测试tf.layers 的dense方法

# todo ,测试方法2，不使用matmul的方法，而是使用nn的方法
layer_dense = tf.layers.dense(units=10,inputs=x,activation=tf.nn.softmax,bias_initializer=tf.zeros_initializer(dtype=tf.float32),kernel_initializer=tf.contrib.layers.xavier_initializer(),reuse=tf.AUTO_REUSE)



In [22]:
# 使用交叉熵的方式，由于已经使用了softmax的方式，所以使用交叉熵
# 交叉熵的计算公式
multi_result =-tf.multiply(y_true, tf.log(layer_dense))
# 求和，获取每个样本的交叉熵
ce2 = tf.reduce_sum(multi_result, reduction_indices=[1])
# 计算整个batch中的交叉熵
cost_2 = tf.reduce_mean(ce2)

In [23]:
# 定义优化器
opt_dense = tf.train.GradientDescentOptimizer(learning_rate=0.01,name="opt_dense")
# 定义train_op
dense_train_op = opt_dense.minimize(loss=cost_2)

In [24]:
def train_dense():
    init = tf.global_variables_initializer()
    sess.run(init)
    show_progress = 200
    batch_size=400
    epoch = 10000
    for i in range(epoch):
        train_batch,label_batch = train_datas.next_batch(batch_size=batch_size)
        #print(type(train_batch))
        #进行训练，并且获取相关的损失
        _,dense_loss_result = sess.run([dense_train_op,cost_2],feed_dict={x:train_batch,y_true:label_batch})
        if i%show_progress==0:
            #print("len(loss):",len(loss_result))
            print("loss:",dense_loss_result)
    


In [25]:
train_dense()

loss: 2.3654234
loss: 1.218252
loss: 0.94215083
loss: 0.72978806
loss: 0.68279207
loss: 0.6112957
loss: 0.5582106
loss: 0.56781477
loss: 0.50211066
loss: 0.50937355
loss: 0.49039987
loss: 0.5126478
loss: 0.49018157
loss: 0.45508453
loss: 0.43765527
loss: 0.42863643
loss: 0.4477783
loss: 0.37186423
loss: 0.46026608
loss: 0.38049802
loss: 0.48695564
loss: 0.420323
loss: 0.41849017
loss: 0.37675434
loss: 0.35345325
loss: 0.33666778
loss: 0.39449012
loss: 0.267374
loss: 0.45822188
loss: 0.37353894
loss: 0.38602868
loss: 0.3411561
loss: 0.3780384
loss: 0.3708429
loss: 0.41722378
loss: 0.36855674
loss: 0.43654642
loss: 0.39785835
loss: 0.34686226
loss: 0.33731872
loss: 0.26470807
loss: 0.34882328
loss: 0.33995017
loss: 0.40003073
loss: 0.39690173
loss: 0.3655105
loss: 0.32998428
loss: 0.37156272
loss: 0.40273207
loss: 0.42162803


In [26]:
# 计算dense的相关的精确率
# 计算相关的精确率
y_test_pred_dense = sess.run(layer_dense,feed_dict={x:mnist.test.images})
# 判断类别是否相等
y_is_equal_dense = tf.equal(tf.arg_max(y_test_pred_dense,dimension=1),tf.arg_max(mnist.test.labels,dimension=1))
# 计算精确率
accu = tf.reduce_mean(tf.cast(y_is_equal_dense,tf.float32))
accu_dense_result = sess.run(accu)
print("accu:",accu_dense_result)

accu: 0.9098
